### PR TITLE
Add Github Pages previews (SOFTWARE-4388)

### PR DESCRIPTION
**Pull request by brianhlin**
Preview repo lives here: https://github.com/opensciencegrid/web-preview/

### CODE REVIEW

**Comment by brianhlin** [comment]
Oops, didn't realize I was working on the same branch as the `robots.txt` change. This is now ready for review @djw8605 @bbockelm. Proposed workflow is:

1. PRs are submitted to `master`, when satisfied, reviewer merges PR into `master`, which triggers a deploy to https://opensciencegrid.org/web-preview/
1. Any additional fixups can be made via step 1.
1. When the website owner is satisfied with the preview, they submit a PR merging `master` into the `production` branch

**Comment by osg-cat** [comment]
> Oops, didn't realize I was working on the same branch as the `robots.txt` change. This is now ready for review @djw8605 @bbockelm. Proposed workflow is:
> 
> 1. PRs are submitted to `master`, when satisfied, reviewer merges PR into `master`, which triggers a deploy to https://opensciencegrid.org/web-preview/
> 2. Any additional fixups can be made via step 1.
> 3. When the website owner is satisfied with the preview, they submit a PR merging `master` into the `production` branch

Could someone please add the final, official process to the README? I makes sense now, but I won’t remember it in 6 months…

**Comment by brianhlin** [comment]
> Could someone please add the final, official process to the README? I makes sense now, but I won’t remember it in 6 months…

Addressed in https://github.com/opensciencegrid/opensciencegrid.github.io/pull/87/commits/0808e4c03815cd5eb3f9c77b6ea57ba0d239ffa3

**Review by djw8605 — APPROVED** [review]
Looks good to me.  Anything left to do?

**Pull request merged**
