### PR TITLE
Possible tweaks to AHM21 page

### PR DESCRIPTION
**Pull request by osg-cat**

### CODE REVIEW

**Comment by osg-cat** [comment]
@jstathas : Take what you like from here.

**Comment by jstathas** [comment]
Hi Tim,


I'm having trouble with the quote block indentation in Markdown.  I did resize and adjust the saturation a bit on the carousel photo. I'll take a look at your suggestions to see if you have ideas on how to correct that.


Thanks and talk to you soon,


Janet


Janet Stathas
PATh Project Manager
Morgridge Institute for Research

Email: jstathas@morgridge.org<mailto:ilandrum@morgridge.org>
Cell:  608.345.9605

https://morgridge.org<https://morgridge.org/>
https://path-cc.io/


________________________________

**Comment by osg-cat** [comment]
My PR does not contain any proposed changes to the home page nor its image. Mine are mostly just typographical suggestions on the AHM21 page.

As for the block quotes — did you look at the generated HTML? They are marked up as block quotes. So apparently it is this theme’s style to just make them normal. Not my first choice, certainly!

**Comment by osg-cat** [comment]
Yeah, so `bootstrap.min.css` includes this:

```
blockquote {
    margin:0 0 1rem
}
```

You get what you pay for!

**Pull request merged**
