### PR TITLE
Added "OSG User School 2018" article & assets

### PR DESCRIPTION
**Pull request by osg-cat**

### CODE REVIEW

**Comment by djw8605** [comment]
Are you sure this is how you want the image to look:
image

**Comment by osg-cat** [comment]
Well, no. But I looked at other articles and that seems to be how we roll now. (T_T) Anyway, just going with conventions.

**Comment by djw8605** [comment]
Using the documentation on the [boostrap website](https://getbootstrap.com/docs/4.0/content/figures/), I was able to fix it to:

image

**Comment by djw8605** [comment]
@osg-cat I edited your branch.  So re-pull from your own repo, then `jekyll serve` to see the difference.

**Comment by osg-cat** [comment]
That’s much nicer. If you are happy with the rest, go ahead and merge.

**Comment by djw8605** [comment]
Yup, I read the text, it reads well.  Merging

**Pull request merged**
