### PR TITLE
Add missing LIGO article (SOFTWARE-3252)

### PR DESCRIPTION
**Pull request by edquist**

### CODE REVIEW

**Comment by edquist** [comment]
@djw8605 please review this one also.

I apparently don't have access to assign/request reviewers.

**Comment by djw8605** [comment]
Oh man, the page looks butchered.  Are you able to preview this on your computer (by installing jekyll?)

Here is a screenshot (ignore the repeated nav bars, that's not a problem):
screenshot-localhost-4000 2018 05 08 15-50-51

**Comment by edquist** [comment]
@djw8605, I found an issue with the inline html that hopefully I've resolved.  Let me know if it looks any better now (or worse).

By the way, I was not able to get github to generate the pages for me nicely in my fork (I got it to publish my commits, it just doesn't look like it's rendering properly), and I am not at all familiar with jekyll.  If you can point me to a doc or recipe for generating the pages that'd be great.  (Thanks!)

**Comment by djw8605** [comment]
Looks much better.

I just installed jekyll on my laptop https://jekyllrb.com/docs/installation/

**Pull request merged**
